### ISSUE TITLE
integration tests experience is obscure

### ISSUE THREAD

**Issue by bernardoaraujor** [antonilol/rust-bitcoincore-zmq#5]
I want to review #4 so I'm trying to run the integration tests on my NixOS 23.05.

I checked out `master` and did:
```
$ nix-shell -p bitcoin
$ cd integration_tests
$  bash test.sh
Bitcoin Core version v25.0.0
Copyright (C) 2009-2023 The Bitcoin Core developers

Please contribute if you find Bitcoin Core useful. Visit
<https://bitcoincore.org/> for further information about the software.
The source code is available from <https://github.com/bitcoin/bitcoin>.

This is experimental software.
Distributed under the MIT software license, see the accompanying file COPYING
or <https://opensource.org/licenses/MIT>

datadir: /run/user/1000/tmp.Q2eSC09Pgj

Bitcoin Core starting

Setting up Bitcoin Core...
{
  "name": "default_wallet"
}
generated 200 blocks

Running tests
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/bitcoincore_zmq_integration_tests`

Bitcoin Core stopping
```

So now I'm confused. Does that mean the tests were successful?

One improvement could be to add `println!` statements after each `assert!` indicating to the user about the success of each test. That would make the experience of running the integration tests a bit more intuitive.

**Comment by antonilol** [comment]
> So now I'm confused. Does that mean the tests were successful?

they were, this integration test script was initially only meant for testing in the github ci, the exit code (0: success, failure otherwise) tells it if it failed or not. a panic or failed assertion prints that it failed

> One improvement could be to add `println!` statements after each `assert!` indicating to the user about the success of each test. That would make the experience of running the integration tests a bit more intuitive.

yeah true, will add this today
